# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-03-08 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_markdown',
            field=models.BooleanField(default=False, verbose_name='\u4f7f\u7528Markdown\u683c\u5f0f'),
        ),
    ]
